# The compiled binary is normalised to this path so that later stages do not
# need to know the Rust target triple it was built for.
ARG BINARY_PATH=/out/app

FROM lukemathwalker/cargo-chef:latest-rust-alpine AS chef
ARG TARGETARCH
RUN apk add --no-cache musl-dev pkgconfig openssl-dev openssl-libs-static upx curl jq
# Map the Docker architecture to the machine name used by Rust target triples and
# by upstream release artifacts. Unsupported architectures fail the build early.
RUN set -eu; \
    case "${TARGETARCH}" in \
        amd64) machine=x86_64 ;; \
        arm64) machine=aarch64 ;; \
        *) echo "unsupported architecture: ${TARGETARCH}" >&2; exit 1 ;; \
    esac; \
    echo "${machine}" > /etc/target-machine; \
    echo "${machine}-unknown-linux-musl" > /etc/target-triple
# Install sentry-cli
RUN set -eu; \
    machine=$(cat /etc/target-machine); \
    latest_version=$(curl -sSf https://api.github.com/repos/getsentry/sentry-cli/releases/latest | jq -r .tag_name); \
    wget -qO /usr/local/bin/sentry-cli "https://downloads.sentry-cdn.com/sentry-cli/${latest_version}/sentry-cli-Linux-${machine}"; \
    chmod +x /usr/local/bin/sentry-cli
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG BINARY_PATH
COPY --from=planner /app/recipe.json recipe.json
RUN set -eu; \
    cargo chef cook --release --target "$(cat /etc/target-triple)" --recipe-path recipe.json
COPY . .
RUN set -eu; \
    target=$(cat /etc/target-triple); \
    cargo build --release --target "${target}"; \
    install -D "target/${target}/release/s3_bucket_perma_link" "${BINARY_PATH}"

# Upload debug symbols to Sentry before stripping
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG VERSION

RUN --mount=type=secret,id=sentry_token \
    if [ -f /run/secrets/sentry_token ]; then \
        sentry-cli debug-files upload \
            --auth-token $(cat /run/secrets/sentry_token) \
            --org ${SENTRY_ORG} \
            --project ${SENTRY_PROJECT} \
            --include-sources \
            ${BINARY_PATH}; \
    fi

# Strip and compress after uploading symbols
RUN strip --strip-all ${BINARY_PATH} && \
    upx --best --lzma ${BINARY_PATH}

# The configuration contract: every key this binary reads, everything it reads outside the
# loader's namespace, and a JSON Schema for the file an operator mounts. Generated from
# `src/config.rs` by the toolchain that built the binary, so it cannot describe a different
# service than the one shipping beside it.
#
# `--format contract` and `--format labels` come out of one invocation of one binary in one
# layer. That is the whole guarantee: the labels the image carries and the document they point at
# are two renderings of a single value, and nothing in between can make them disagree.
FROM builder AS contract-builder

# Deliberately without the default the runtime stage below gives the same name. An unset release
# is *absent* from the document, where `unknown` would be a claim about which release it
# describes — and `--version` refuses an empty value rather than publishing one.
ARG version

RUN set -eu; \
    target=$(cat /etc/target-triple); \
    mkdir -p /out; \
    if [ -n "${version:-}" ]; then set -- --version "${version}"; else set --; fi; \
    cargo run --quiet --release --target "${target}" --example config-schema \
        -- --format contract "$@" > /out/contract.json; \
    cargo run --quiet --release --target "${target}" --example config-schema \
        -- --format labels > /out/contract.labels

# The two generated files and nothing else, so exporting them with `--output type=local` costs a
# two-file layer rather than an export of the whole builder filesystem. This is what the label
# check reads, and what `oras attach` publishes; see `.github/scripts/check-contract-labels.sh`.
FROM scratch AS contract
COPY --from=contract-builder /out/contract.json /out/contract.labels /

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b AS env

RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache ca-certificates mailcap tzdata

RUN update-ca-certificates

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "10001" \
    "appuser"

FROM scratch AS runtime

ARG BINARY_PATH

ARG version=unknown
ARG release=unreleased

LABEL version=${version} \
      release=${release}

# The offline copy of the configuration contract, for a `docker save` tarball, an air-gapped
# mirror or an in-cluster reader. The chart repository reads whichever of this and the copy
# attached to the digest it can reach, and refuses the image when the two differ.
COPY --from=contract-builder /out/contract.json /config/contract.json

# Generated by `cargo run --example config-schema -- --format dockerfile`. Do not edit by hand:
# `.github/scripts/check-contract-drift.sh` diffs this block against that command's output, and
# `.github/scripts/check-contract-labels.sh` then checks the labels the *image* actually carries
# against what the same generator wrote inside the build.
#
# A `LABEL` key cannot be interpolated, and the document is produced inside a builder stage the
# host's `docker build` command line cannot reach — so hand-writing these is unavoidable, and the
# check on the built image is what makes it safe.
# contract-labels:begin
LABEL dev.terrace.config.contract.version="1" \
      dev.terrace.config.contract.path="/config/contract.json" \
      dev.terrace.config.prefix="S3_PERMA_LINK_"
# contract-labels:end

COPY --from=env /etc/passwd /etc/passwd
COPY --from=env /etc/group /etc/group
COPY --from=env /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=env /usr/share/zoneinfo /usr/share/zoneinfo

WORKDIR /app
COPY --from=builder --chown=root:root ${BINARY_PATH} ./app

USER 1000:1000

CMD ["./app"]
